### ISSUE TITLE
error: #[feature] may not be used on the [beta, stable, or nightly] channel

### ISSUE THREAD

**Issue by Bluebird45** [PistonDevelopers/current#106]
I'm getting a compile error no matter which Rust compiler I try, on Debian 8.3 64-bit, with Rustup.

I first noticed it when I tried to compile Dyon, which has Current as a dependency. Nevertheless, the problem needs reporting here.

Since the readme for Dyon specifies "Rust 1.8 beta or newer" then I thought to try different versions of Rust, since 1.8 went from beta to stable a few weeks ago, but I've been unable to locate a version that compiles Current.

I found a version of Rust in the [Rust archive](http://static.rust-lang.org/dist/index.html "Rust archive") from when 1.8 was beta (use "rustup default beta-2016-03-23-x86_64-unknown-linux-gnu" to get it) but that gave the same error.

The previous subversion of Current (0.1.0) also fails with the same error.

Is this a problem with Rust or Current, or am I just doing something wrong?

````
$ rustc -V
rustc 1.8.0 (db2939409 2016-04-11)
$ cargo clean
$ cargo build
Compiling current v0.1.1 (file:///home/user/projects/current)
src/lib.rs:2:1: 2:29 error: #[feature] may not be used on the stable release channel
src/lib.rs:2 #![feature(core_intrinsics)]
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `current`.
````

**Comment by bvssvni** [comment]
I belive you need the nightly version.

**Comment by Bluebird45** [comment]
Thanks, it compiles with the current nightly. I was trying everything else.
